// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMqgbbq_l9DwdQr6flFgMGpo8K42oyoLc',
    appId: '1:682831271155:web:946406a23204788c98d386',
    messagingSenderId: '682831271155',
    projectId: 'loaclfix',
    authDomain: 'loaclfix.firebaseapp.com',
    storageBucket: 'loaclfix.firebasestorage.app',
    measurementId: 'G-HR72KPBRFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdDkcOBkRYrJ8DGmL4bzb8fryMOgdUCgU',
    appId: '1:682831271155:android:d8c9d1f746bd162498d386',
    messagingSenderId: '682831271155',
    projectId: 'loaclfix',
    storageBucket: 'loaclfix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAneGJFnYhZBwwCRjjxnbEV0UxkbSqMqdA',
    appId: '1:682831271155:ios:49812fd54291c30098d386',
    messagingSenderId: '682831271155',
    projectId: 'loaclfix',
    storageBucket: 'loaclfix.firebasestorage.app',
    iosBundleId: 'com.example.localfix',
  );
}
